file_format: "1"
id: dactyl
name: Dactyl
type: shield
url: https://github.com/foostan/crkbd/
requires:
  - pro_micro
features:
  - keys
  # - display
  # - underglow
  # - backlight
  # - pointer
siblings:
  - dactyl_left
  - dactyl_right